rootUrl: http://localhost:8080/components/vaadin-dropdown-menu/test/visual/
gridUrl: http://localhost:4444/wd/hub
screenshotsDir: ./test/visual/screens

system:
  plugins:
    polyserve:
      port: 8080
    sauce: true

browsers:
  ie:
    desiredCapabilities:
      browserName: "internet explorer"
      version: "11.0"
      platform: "Windows 10"
